# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2179dc698662a63036a9b627e17fca28ae8ebfbed089124054af8b269f3b06670155907587c051d718dd8e8180a281389671faaa5c392617d69c5b620e1370c1

test:
  secret_key_base: 419cf10ac164617e8f02988a057851c5bf84ea5396a2761966229e48de46facf9ab9d3f7b467c64613fa9345aaceb7d9c70761a54c8726b6acb860708b2a4680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
